---
- name: Deploy Flask App
  hosts: ec2
  become: true

  tasks:
  - name: Pull Docker image
    docker_image:
      name: ahmeddarder1/dr
      source: pull

  - name: Run Docker container
    docker_container:
      name: flask_app
      image: ahmeddarder1/dr
      ports:
      - "80:5000"
      state: started
      command: "python -m pytest tests"
      detach: yes
      command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  - name: Wait for container to start
    uri:
      url: http://localhost
      status: 200
    register: result
    until: result.status == 200
    retries: 10
    delay: 5

  - name: Test Flask app
    uri:
      url: http://localhost
      status: 200
    register: result
    until: result.status == 200
    retries: 10
    delay: 5
 
