---
- name: Deploy my_flask_app to Kubernetes
  hosts: 44.220.150.183 , 3.235.192.151
  become: true
  tasks:
  - name: Deploy Docker image
    kubernetes:
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: flask_app
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: flask_app
          template:
            metadata:
              labels:
                app: flask_app
            spec:
              containers:
              - name: flask_app
                image: ahmeddarder1/dr
                ports:
                - containerPort: 5000
