---
- name: Deploy application
  hosts: ec2
  become: true

  tasks:
  - name: Pull Docker image
    docker_image:
      name: ahmeddarder1/dr
      source: pull
      sleep : 100

  - name: Run Docker container
    docker_container:
      name: flask_app
      image: ahmeddarder1/dr
      ports:
      - "80:5000"
      state: started
      command: sleep 100
      detach: yes
