---
- name: Deploy Flask App
  hosts: ec2
  become: true

  tasks:
  - name: Install dependencies
    apt:
      name: python3-pip
      state: present

  - name: Install Flask
    pip:
      name: flask
      state: present

  - name: Clone repository
    git:
      repo: https://github.com/Drdr1/Depi-project/tree/main
      dest: /home/ubuntu/flask-app

  - name: Install requirements
    pip:
      requirements: /home/ubuntu/flask-app/requirements.txt

  - name: Start Flask app
    shell: |
      cd /home/ubuntu/flask-app
      python3 app.py
    async: 1000
    poll: 0
    ignore_errors: true
    become: true

  - name: Ensure Flask app is running
    uri:
      url: http://localhost:5000
      status: 200
    register: result
    until: result.status == 200
    retries: 10
    delay: 5
